---
- name: Install python3-debian for repository management
  ansible.builtin.apt:
    name: python3-debian
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Add misc-pkg repository
  ansible.builtin.deb822_repository:
    name: misc-pkg
    types: deb
    uris: https://kakwa.github.io/misc-pkg/deb.{{ ansible_facts['lsb']['codename'] }}.arm64/
    suites: "{{ ansible_facts['lsb']['codename'] }}"
    components: main
    architectures: arm64
    signed_by: https://kakwa.github.io/misc-pkg/GPG-KEY.pub
