---
- name: Setup BTT SKR3 CNC Machine
  hosts: all
  #become: true

  vars:
    # Avahi configuration (for mDNS/SSH announcement)
    avahi_hostname: "kwcnc"
    avahi_domain_name: "local"
    avahi_service_enabled: true
    avahi_service_state: started
  
  roles:
    # Local custom roles
    - { role: hostname, tags: ["system", "hostname"] }
    - { role: rsyslog, tags: ["system", "rsyslog"] }
    - { role: repos, tags: ["system", "repos"] }
    - { role: avahi, tags: ["system", "network", "avahi"] }
    - { role: nginx, tags: ["system", "network", "nginx"] }
    - { role: gsender, tags: ["apps", "gsender"] }
    - { role: grblhal-builder, tags: ["development", "grblhal"] }
    - { role: cnc-console, tags: ["apps", "cnc-console"] }
