---
- name: Setup BTT SKR3 CNC Machine
  hosts: all
  #become: true

  vars:
    # grblHAL machine-specific build flags injected into [env:kwcnc_yeti] in platformio.ini
    grblhal_machine_build_flags:
      - "!echo \"-D BUILD_INFO='\\\"KWCNC_$(date +%%Y%%m%%d_%%H%%M)\\\"'\""
      - "-D X_GANGED=1"
      - "-D X_AUTO_SQUARE=0"
      - "-D X_GANGED_LIM_MAX=0"
      - "-D Y_GANGED=1"
      - "-D Y_AUTO_SQUARE=0"
      - "-D Y_GANGED_LIM_MAX=0"
      - "-D Z_GANGED=0"
      - "-D Z_AUTO_SQUARE=0"
      - "-D Z_GANGED_LIM_MAX=0"
      - "-D DEFAULT_X_CURRENT=1000.0f"
      - "-D DEFAULT_Y_CURRENT=1000.0f"
      - "-D DEFAULT_Z_CURRENT=1000.0f"
      - "-D DEFAULT_A_CURRENT=1000.0f"
      - "-D DEFAULT_B_CURRENT=1000.0f"
      - "-D DEFAULT_X_STEPS_PER_MM=56.8f"
      - "-D DEFAULT_Y_STEPS_PER_MM=56.8f"
      - "-D DEFAULT_Z_STEPS_PER_MM=1065.0f"
      - "-D DEFAULT_A_STEPS_PER_MM=56.8f"
      - "-D DEFAULT_B_STEPS_PER_MM=56.8f"
      - "-D DEFAULT_DIR_SIGNALS_INVERT_MASK=0"
      - "-D DEFAULT_HOMING_DIR_MASK=3"
      - "-D DEFAULT_X_MAX_RATE=5000.0f"
      - "-D DEFAULT_Y_MAX_RATE=5000.0f"
      - "-D DEFAULT_Z_MAX_RATE=500.0f"
      - "-D DEFAULT_X_ACCELERATION=30.0f"
      - "-D DEFAULT_Y_ACCELERATION=30.0f"
      - "-D DEFAULT_Z_ACCELERATION=10.0f"
      - "-D DEFAULT_X_MAX_TRAVEL=1400.0f"
      - "-D DEFAULT_Y_MAX_TRAVEL=2500.0f"
      - "-D DEFAULT_Z_MAX_TRAVEL=180.0f"
      - "-D DEFAULT_PROBE_SIGNAL_INVERT=1"
      - "-D DEFAULT_HARD_LIMIT_ENABLE=1"
      - "-D DEFAULT_CHECK_LIMITS_AT_INIT=1"
      - "-D CONTROL_ENABLE=1"
      - "-D COOLANT_ENABLE=0"
      - "-D ESP_AT_ENABLE=0"
      - "-D PROBE_ENABLE=1"
      - "-D SAFETY_DOOR_ENABLE=0"
      - "-D ESTOP_ENABLE=1"
      - "-D TRINAMIC_UART_ENABLE=0"
      - "-D TRINAMIC_SPI_ENABLE=1"
      - "-D TRINAMIC_ENABLE=5160"
    # Avahi configuration (for mDNS/SSH announcement)
    avahi_hostname: "kwcnc"
    avahi_domain_name: "local"
    avahi_service_enabled: true
    avahi_service_state: started
  
  roles:
    # Local custom roles
    - { role: hostname, tags: ["system", "hostname"] }
    - { role: rsyslog, tags: ["system", "rsyslog"] }
    - { role: repos, tags: ["system", "repos"] }
    - { role: avahi, tags: ["system", "network", "avahi"] }
    - { role: nginx, tags: ["system", "network", "nginx"] }
    - { role: gsender, tags: ["apps", "gsender"] }
    - { role: grblhal-builder, tags: ["development", "grblhal"] }
    - { role: cnc-console, tags: ["apps", "cnc-console"] }
